### ISSUE TITLE
Integration stopped working after OS update 14.0 and Core update 2024.12.0

### ISSUE THREAD

**Issue by OverlordPotato1** [dudanov/hassio-ftms#17]
After updating to Home Assistant Operating System to 14.0 and Home Assistant Core to 2024.12.0, interacting with the integration in any way gives
`Failed to perform the action button/press. issubclass() arg 1 must be a class`
or
`Failed to perform the action number/set_value. issubclass() arg 1 must be a class`

Logs:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:49:18 (5 occurrences)
Last logged: 16:55:30

[140265641586848] Unexpected exception
[140265962461440] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
    await self.async_press()
  File "/config/custom_components/ftms/button.py", line 52, in async_press
    await self.ftms.start_resume()
  File "/usr/local/lib/python3.13/site-packages/pyftms/client/client.py", line 290, in start_resume
    return await self._write_command(ControlCode.START_RESUME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyftms/client/client.py", line 278, in _write_command
    return await self._controller.write_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._cli, code, timeout=self._timeout, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyftms/client/backends/controller.py", line 141, in write_command
    await self.write_command(
    ...<3 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/pyftms/client/backends/controller.py", line 150, in write_command
    request._serialize(bio)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 146, in _serialize
    for field, serializer in self._iter_fields_serializers():
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 112, in _iter_fields_serializers
    serializers = _get_model_serializers(cls)
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 98, in _get_model_serializers
    result[field.name] = _get_model_field_serializer(field)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 88, in _get_model_field_serializer
    return _get_serializer(type_)
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 69, in _get_serializer
    if issubclass(type_, (int, float)):
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
```

Treadmill information from the device page:
```
T4020-0x06
by AKSO-0x23
Firmware: 1.2.0
Hardware: 1.0.0
Serial number: AK-TM-T
Bluetooth: 50:54:7B:0A:E9:3C
```

**Comment by dudanov** [comment]
Fixed in [v0.24.1](https://github.com/dudanov/hassio-ftms/releases/tag/v0.24.1).
