### ISSUE TITLE
BLACK LORD Treadmill - Walking Pad SL9

### ISSUE THREAD

**Issue by redcoelho** [dudanov/hassio-ftms#9]
The `BLACK LORD Treadmill - Walking Pad SL9` has a "Fitshow SmartBTM Bluetooth module" which according to this [Reddit post](https://www.reddit.com/r/treadmills/comments/1cbhemd/mobile_app_to_track_under_desk_treadmill_walks/)  "has complete support of the Bluetooth FTMS standard".

However, when I try to configure the "Fitness Machine  Service" in HA it gives an error without any details. When I try again it gives:

> Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by redcoelho** [comment]
Log details
```
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 550, in call_configure
    await self._async_configure(flow.flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ftms/config_flow.py", line 251, in async_step_ble_request
    _LOGGER.debug(f"Supported ranges: {self._ftms.supported_ranges}")
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyftms/client/client.py", line 223, in supported_ranges
    return self._settings_ranges
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Treadmill' object has no attribute '_settings_ranges'
```

When I get a chance I'll try debugging with pyftms.

**Comment by ArcherFromGrodno** [comment]
This is probably a related issue with this topic: https://github.com/dudanov/hassio-ftms/issues/16

**Comment by redcoelho** [comment]
Tried this again after a long break and now it works! Thank you!
